version: "3.8"

services:
  db:
    image: postgres:15
    container_name: imgharvest_db
    environment:
      POSTGRES_USER: harvest_admin
      POSTGRES_PASSWORD: harvest_password
      POSTGRES_DB: imgharvest
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data_final:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped
