[package]
org = "imgharvest"
name = "image_service"
version = "0.1.0"
distribution = "2201.13.1"

[build-options]
observabilityIncluded = false

[[platform.java17.dependency]]
path = "./libs/zip-creator.jar"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "3.2.0"
